# Generated by Django 4.2.5 on 2023-10-05 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
